# -*- coding: utf-8 -*-
"""app.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1ZuHiytP6fwluazOKBTJSAzNMoglrRAYc
"""
import streamlit as st          # framework UI utama
import requests                 # untuk kirim HTTP request ke API prediksi

st.set_page_config(
    page_title="SVM Prediction",  # judul tab browser
    layout="wide"                 # gunakan lebar layar penuh, bukan mode default sempit
)

# ---- Custom CSS untuk mempercantik tampilan ----
st.markdown("""
<style>
.main-title {
    font-size: 2.5rem;
    font-weight: 800;
    background: -webkit-linear-gradient(45deg, #6a11cb, #2575fc);  /* gradasi ungu-biru */
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;   /* trik CSS agar teks jadi gradasi warna */
    margin-bottom: 0;
}
.subtitle {
    color: #888;             /* abu-abu, untuk teks pendukung di bawah judul */
    font-size: 1.1rem;
    margin-top: 0;
}
.result-box {
    padding: 1.5rem;         /* kotak pembungkus hasil prediksi */
    border-radius: 12px;     /* sudut membulat */
    margin-top: 1rem;
    text-align: center;
}
.benign {
    background: linear-gradient(135deg, #d4fc79, #96e6a1);  /* hijau = kasus jinak */
    color: #1b5e20;
}
.malignant {
    background: linear-gradient(135deg, #ff9a9e, #fecfef);  /* merah muda = kasus ganas */
    color: #b71c1c;
}
.stButton>button {
    background: linear-gradient(45deg, #6a11cb, #2575fc);   /* styling tombol Predict */
    color: white;
    border-radius: 8px;
    padding: 0.6rem 1.5rem;
    border: none;
    font-weight: 600;
    width: 100%;              /* tombol memenuhi lebar kolomnya */
}
</style>
""", unsafe_allow_html=True)   # wajib True agar CSS custom benar-benar dirender, bukan ditampilkan sebagai teks mentah

st.markdown('<p class="main-title">🩺 Breast Cancer Prediction</p>', unsafe_allow_html=True)  # judul utama pakai style .main-title
st.markdown('<p class="subtitle">Model Support Vector Machine (SVM) untuk klasifikasi tumor</p>', unsafe_allow_html=True)  # subjudul penjelas
st.divider()   # garis pemisah horizontal bawaan Streamlit

st.subheader("📋 Input 30 Fitur")   # header bagian input
st.caption("Masukkan nilai fitur hasil pemeriksaan sel di bawah ini")  # teks kecil instruksi

inputs = []
cols = st.columns(3)  # bagi layar jadi 3 kolom sejajar agar 30 input tidak memanjang ke bawah
for i in range(30):
    with cols[i % 3]:                              # distribusikan input ke kolom 1,2,3,1,2,3,...
        value = st.number_input(f"Feature {i+1}", key=f"feat_{i}")  # key unik wajib karena ada di dalam loop
        inputs.append(value)                        # kumpulkan semua nilai untuk dikirim ke API

st.divider()

predict_clicked = st.button("🔍 Predict")   # tombol trigger prediksi

if predict_clicked:
    url = "http://127.0.0.1:8000/predict"   # endpoint API lokal (tidak diverifikasi hidup/tidaknya dari sini)
    with st.spinner("Sedang memproses prediksi..."):  # animasi loading selama request berjalan
        response = requests.post(
            url,
            json={
                "features": inputs      # payload sesuai kontrak API asli, tidak diubah
            }
        )
    hasil = response.json()   # asumsi: response selalu 200 dan valid JSON — tidak ada penanganan error

    pred_label = hasil['prediction']   # ambil label prediksi dari response
    prob = hasil['probability']        # ambil probabilitas dari response

    # PERINGATAN: baris berikut adalah ASUMSI saya terhadap format label API Anda, bukan fakta terverifikasi
    box_class = "malignant" if str(pred_label).lower() in ["malignant", "1"] else "benign"
    icon = "⚠️" if box_class == "malignant" else "✅"   # ikon berbeda tergantung hasil klasifikasi

    st.markdown(
        f"""
        <div class="result-box {box_class}">
            <h2>{icon} Prediction: {pred_label}</h2>
        </div>
        """,
        unsafe_allow_html=True   # render HTML kustom, bukan teks polos
    )

    col1, col2 = st.columns([1, 2])   # bagi area hasil jadi 2 kolom, kolom kanan lebih lebar
    with col1:
        st.metric("Probability", f"{prob:.2%}")   # tampilkan angka probabilitas dalam format %
    with col2:
        st.progress(min(max(prob, 0.0), 1.0))      # bar visual; di-clamp 0–1 agar tidak error jika prob di luar rentang
