"""app.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1ZuHiytP6fwluazOKBTJSAzNMoglrRAYc
"""
import streamlit as st
import requests

st.set_page_config(
    page_title="SVM Prediction",
    layout="wide"
)

# ---- CSS: gaya klinis ala website kesehatan luar negeri ----
st.markdown("""
<style>
/* Judul bawaan st.title("Breast Cancer Prediction") */
h1 {
    font-family: -apple-system, "Segoe UI", "Helvetica Neue", Arial, sans-serif;
    color: #0B3D66;              /* navy medis solid */
    font-weight: 700;
    letter-spacing: -0.5px;
}

/* Teks bawaan st.write() */
[data-testid="stMarkdownContainer"] p {
    font-family: -apple-system, "Segoe UI", Arial, sans-serif;
    color: #5A6B7B;               /* abu kebiruan, kesan formal */
}

/* Tombol Predict */
.stButton>button {
    background-color: #0E7C86;    /* teal medis solid, bukan gradasi */
    color: white;
    border-radius: 6px;
    padding: 0.6rem 1.5rem;
    border: none;
    font-weight: 600;
    width: 100%;
}
.stButton>button:hover {
    background-color: #0B6069;
}

/* Kotak hasil st.success() */
[data-testid="stAlertContentSuccess"] {
    background-color: #F1F8F2;
    border-left: 5px solid #2E7D32;   /* border kiri, gaya kartu hasil lab */
    border-radius: 6px;
    color: #1B4620;
}

/* Angka metric st.metric() (Probability) */
[data-testid="stMetricValue"] {
    color: #0B3D66;
    font-family: -apple-system, "Segoe UI", Arial, sans-serif;
}
[data-testid="stMetricLabel"] {
    color: #5A6B7B;
}
</style>
""", unsafe_allow_html=True)

st.title("Breast Cancer Prediction")
st.write("Input 30 Feature")
inputs=[]
for i in range(30):
    value=st.number_input(f"Feature {i+1}")
    inputs.append(value)
if st.button("Predict"):
    url="http://https://sipkol-jagkqkj9fcsvkbu5ip7nzn.streamlit.app//predict"
    response=requests.post(
        url,
        json={
            "features":inputs
        }
    )
    hasil=response.json()
    st.success(f"Prediction : {hasil['prediction']}")
    st.metric("Probability",f"{hasil['probability']:.2%}")
